CREATE TABLE users(
    uuid INTEGER NOT NULL PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(40) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entries(
    entryid INTEGER NOT NULL PRIMARY KEY,
    owner INTEGER NOT NULL,
    link VARCHAR(256) NOT NULL,
    title VARCHAR NOT NULL,
    snippet VARCHAR NOT NULL,
    usernotes VARCHAR,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY(owner) REFERENCES users (uuid)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE tags(
    tagid INTEGER NOT NULL PRIMARY KEY,
    tagvalue VARCHAR(32) NOT NULL,
    owner INTEGER NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        FOREIGN KEY(owner) REFERENCES users(uuid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY(tagid) REFERENCES entries (entryid)
        ON UPDATE CASCADE
        ON DELETE CASCADE 
);